[colors.primary]
background = "#161616"
foreground = "#f2f4f8"

[colors.normal]
black   = "#262626"
red     = "#ff7eb6"
green   = "#42be65"
yellow  = "#08bdba"
blue    = "#78a9ff"
magenta = "#be95ff"
cyan    = "#33b1ff"
white   = "#dde1e6"

[colors.bright]
black   = "#393939"
red     = "#ff7eb6"
green   = "#42be65"
yellow  = "#08bdba"
blue    = "#78a9ff"
magenta = "#be95ff"
cyan    = "#33b1ff"
white   = "#f2f4f8"
